kind: CronJob
apiVersion: "batch/v1beta1"
metadata:
  name: "cronjob-ldap-group-sync"
  namespace: "test-ldap"
  labels:
    template: "cronjob-ldap-group-sync"
spec:
  schedule: "@hourly"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: "5"
  failedJobsHistoryLimit: "5"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: "cronjob-ldap-group-sync"
              image: "registry.access.redhat.com/openshift3/ose-cli:v3.11"
              command:
                - "/bin/bash"
                - "-c"
                - oc adm groups sync --sync-config=/etc/config/ldap-group-sync.yaml --confirm
                  $([ -s /etc/config/whitelist.txt ] && echo --whitelist=/etc/config/whitelist.txt)
              volumeMounts:
                - mountPath: "/etc/config"
                  name: "ldap-sync-volume"
                - mountPath: "/etc/secrets"
                  name: "ldap-bind-password"
          volumes:
            - name: "ldap-sync-volume"
              configMap:
                name: "ldap-config"
            - name: "ldap-bind-password"
              secret:
                secretName: "ldap-bind-password"
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 500
          dnsPolicy: "ClusterFirst"
          serviceAccountName: "ldap-group-syncer"
          serviceAccount: "ldap-group-syncer"
  startingDeadlineSeconds: 60
