apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - configMapFromVault.yaml
  - secretFromVault.yaml
resources:
  - whitelist-configmap.yaml
  - clusterrole.yaml
  - service-account.yaml
  - clusterrolebinding-yaml
