kind: LDAPSyncConfig
apiVersion: v1
bindDN: "vault://caas/data/sync-ldap@bindDN"
bindPassword: "vault://caas/data/sync-ldap@bindPassword"
url: "vault://caas/data/sync-ldap@ldapURL"
insecure: true
rfc2307:
  groupsQuery:
    baseDN: "vault://caas/data/sync-ldap@queryBaseDNGroups"
    scope: sub
    derefAliases: never
    pageSize: 0
    filter: "vault://caas/data/sync-ldap@ldapFilter"
  groupUIDAttribute: cn
  groupNameAttributes: [ cn ]
  groupMembershipAttributes: [ member ]
  usersQuery:
    baseDN: "vault://caas/data/sync-ldap@queryBaseDNUsers"
    scope: sub
    derefAliases: never
    pageSize: 0
  userUIDAttribute: dn
  userNameAttributes: [ corpAliasLocal ]
  tolerateMemberNotFoundErrors: true
  tolerateMemberOutOfScopeErrors: false
